import { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import Icon from '../components/ui/Icon';
import DeviceScene from '../components/3d/DeviceScene';
import { createBooking, getUnavailableSlots } from '../services/backend';
import styles from './Booking.module.css';

const SERVICES=['Screen Replacement','Battery Replacement','Water Damage Recovery','Motherboard / Chip-Level','Data Recovery','Software Fix / Flashing','Camera Repair','Charging Port Repair','Other / Not Sure'];
const DEVICES=[{label:'iPhone',icon:'phone',pickup:true},{label:'Android Phone',icon:'phone',pickup:true},{label:'MacBook',icon:'laptop',pickup:true},{label:'Windows Laptop',icon:'monitor',pickup:true},{label:'iPad / Tablet',icon:'tablet',pickup:true}];
const TIME_SLOTS=['10:00 AM','10:30 AM','11:00 AM','11:30 AM','12:00 PM','12:30 PM','01:00 PM','01:30 PM','02:00 PM','02:30 PM','03:00 PM','03:30 PM','04:00 PM','04:30 PM','05:00 PM','05:30 PM','06:00 PM','06:30 PM','07:00 PM','07:30 PM'];
const STEP_LABELS=['Method','Device','Repair','Time','Details','Confirm'];

function getNext7Days(){const out=[];const now=new Date();const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];for(let i=0;i<7;i++){const d=new Date(now);d.setDate(now.getDate()+i);const value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;out.push({label:i===0?'Today':i===1?'Tomorrow':days[d.getDay()],sub:`${d.getDate()} ${months[d.getMonth()]}`,full:d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}),value})}return out}
function slotPast(date,slot){if(!date)return false;const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;if(date!==today)return false;const [time,ap]=slot.split(' ');let[h,m]=time.split(':').map(Number);if(ap==='PM'&&h!==12)h+=12;if(ap==='AM'&&h===12)h=0;return h*60+m<=now.getHours()*60+now.getMinutes()+20}
const digits=v=>v.replace(/\D/g,'');

export default function Booking({ embedded=false, defaultMethod='' }){
  const navigate=useNavigate(); const [params]=useSearchParams(); const days=useMemo(getNext7Days,[]);
  const initialMethod=defaultMethod || (params.get('method')==='pickup'?'pickup':'');
  const [step,setStep]=useState(initialMethod?2:1); const [method,setMethod]=useState(initialMethod); const [device,setDevice]=useState(''); const [service,setService]=useState(''); const [selectedDay,setSelectedDay]=useState(null); const [selectedSlot,setSelectedSlot]=useState('');
  const [form,setForm]=useState({name:'',phone:'',email:'',model:'',address:'',area:'',landmark:'',pincode:'',mapLink:'',notes:''});
  const [unavailable,setUnavailable]=useState([]); const [availability,setAvailability]=useState('idle'); const [submitStatus,setSubmitStatus]=useState('idle'); const [error,setError]=useState(''); const [booking,setBooking]=useState(null);

  useEffect(()=>{if(!selectedDay)return;let live=true;setAvailability('loading');getUnavailableSlots(selectedDay.value,method||'store').then(v=>{if(live){setUnavailable(v);setAvailability('ready')}}).catch(()=>{if(live){setUnavailable([]);setAvailability('error')}});return()=>{live=false}},[selectedDay,method]);
  useEffect(()=>{if(selectedSlot&&(unavailable.includes(selectedSlot)||slotPast(selectedDay?.value,selectedSlot)))setSelectedSlot('')},[unavailable,selectedDay,selectedSlot]);

  const phoneDigits=digits(form.phone); const phoneOk=phoneDigits.length>=10&&phoneDigits.length<=15; const pickup=method==='pickup';
  const pincodeOk=!pickup||(digits(form.pincode).length>=5&&digits(form.pincode).length<=8); const nameOk=form.name.trim().length>=2;
  const canProceed=()=>{
    if(step===1)return !!method;
    if(step===2)return !!device;
    if(step===3)return !!service;
    if(step===4)return !!selectedDay&&!!selectedSlot;
    if(step===5)return nameOk&&phoneOk&&form.model.trim().length>=2&&(!pickup||(form.address.trim().length>=5&&form.area.trim().length>=2&&pincodeOk));
    return true;
  };
  const next=()=>{setError('');if(canProceed())setStep(s=>Math.min(6,s+1));else setError('Please complete the required selection/details before continuing.')};
  const back=()=>{setError('');setStep(s=>Math.max(1,s-1))};
  const selectMethod=m=>{setMethod(m)};
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));

  const submit=async()=>{setSubmitStatus('sending');setError('');try{const result=await createBooking({repair_method:method,device_type:device,device_model:form.model,service,appointment_date:selectedDay.value,appointment_time:selectedSlot,customer_name:form.name,phone:form.phone,email:form.email||null,address:pickup?form.address:null,area:pickup?form.area:null,landmark:pickup?form.landmark:null,pincode:pickup?form.pincode:null,map_link:pickup?form.mapLink:null,notes:form.notes||null});setBooking(result);setSubmitStatus('success')}catch(e){setSubmitStatus('error');setError(String(e?.message||'Booking could not be completed. If this slot was just taken, choose another time.'))}};

  if(submitStatus==='success'&&booking)return <section className={styles.successPage}><div className="container"><motion.div className={styles.successCard} initial={{opacity:0,scale:.96,y:20}} animate={{opacity:1,scale:1,y:0}}><div className={styles.successIcon}><Icon name="check" size={38}/></div><span className="tag">Booking received</span><h1>{pickup?'Pickup requested':'Appointment requested'}</h1><p>{pickup?'iHub can confirm pickup coverage and collection timing using your registered phone/WhatsApp number.':'Your selected appointment has been recorded. iHub can contact you if any timing adjustment is needed.'}</p><div className={styles.reference}><span>Booking Reference</span><strong>{booking.tracking_id}</strong><small>Use this reference when contacting iHub about your booking.</small></div><div className={styles.successActions}><a href={`https://wa.me/919025790266?text=Hi%2C%20my%20iHub%20booking%20reference%20is%20${encodeURIComponent(booking.tracking_id)}`} target="_blank" rel="noopener" className="btn-primary brand-grad">WhatsApp iHub</a><button className="btn-secondary" onClick={()=>navigate('/')}>Home</button></div></motion.div></div></section>;

  return <>
    {!embedded&&<section className={styles.hero}><div className="container"><div className={styles.heroGrid}><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}}><span className="tag">Book repair</span><h1>Choose store visit or <span className="brand-text">free pickup & delivery.</span></h1><p>A single booking flow for device, repair, real slot availability, customer details and doorstep pickup address.</p></motion.div><DeviceScene compact highlight={service.includes('Battery')?'battery':service.includes('Screen')?'screen':service.includes('Camera')?'camera':service.includes('Charging')?'port':service.includes('Motherboard')?'board':''}/></div></div></section>}
    <section id={embedded?'book-repair':undefined} className={`${styles.bookingSec} ${embedded?styles.embeddedSec:''}`}><div className="container"><div className={styles.wrapper}>
      <div className={styles.stepBar}>{STEP_LABELS.map((label,i)=>{const n=i+1;return <div key={label} className={`${styles.stepItem} ${step===n?styles.stepActive:''} ${step>n?styles.stepDone:''}`}><div className={styles.stepBubble}>{step>n?'✓':n}</div><div className={styles.stepLabel}>{label}</div></div>})}</div>
      <div className={styles.card}><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-16}} transition={{duration:.25}}>
        {step===1&&<><div className={styles.cardHeader}><h2>How should we receive the device?</h2><p>Free doorstep pickup and return is available for supported phones, MacBooks, Windows laptops and tablets in eligible service areas. Store Visit remains available too.</p></div><div className={styles.methodGrid}><button className={`${styles.methodCard} ${method==='store'?styles.selected:''}`} onClick={()=>selectMethod('store')}><span className={styles.methodIcon}><Icon name="pin" size={30}/></span><strong>Visit iHub Store</strong><p>Choose a repair appointment and bring the device to the Nagercoil shop.</p><span className={styles.methodMeta}>All supported devices</span></button><button className={`${styles.methodCard} ${method==='pickup'?styles.selected:''}`} onClick={()=>selectMethod('pickup')}><span className={styles.freeBadge}>FREE</span><span className={styles.methodIcon}><Icon name="truck" size={31}/></span><strong>Pickup & Delivery</strong><p>Doorstep collection and return for eligible supported-device repair bookings.</p><span className={styles.methodMeta}>Phones · laptops · tablets · eligible areas</span></button></div></>}
        {step===2&&<><div className={styles.cardHeader}><h2>Select your device</h2><p>{pickup?'Choose any supported device for eligible free pickup and return delivery.':'Choose the device you want iHub to diagnose.'}</p></div><div className={styles.deviceGrid}>{DEVICES.map(d=><button key={d.label} className={`${styles.deviceBtn} ${device===d.label?styles.selected:''}`} onClick={()=>setDevice(d.label)}><span className={styles.deviceIcon}><Icon name={d.icon} size={30}/></span><strong>{d.label}</strong></button>)}</div></>}
        {step===3&&<><div className={styles.cardHeader}><h2>What repair do you need?</h2><p>Choose the closest option. iHub can refine the diagnosis after inspection.</p></div><div className={styles.serviceList}>{SERVICES.map(s=><button key={s} className={`${styles.serviceBtn} ${service===s?styles.selected:''}`} onClick={()=>setService(s)}><span>{s}</span>{service===s&&<Icon name="check" size={18}/>}</button>)}</div></>}
        {step===4&&<><div className={styles.cardHeader}><h2>{pickup?'Choose pickup window':'Choose appointment time'}</h2><p>Unavailable slots come from the booking data source instead of hard-coded demo values.</p></div><div className={styles.dayRow}>{days.map(d=><button key={d.value} className={`${styles.dayBtn} ${selectedDay?.value===d.value?styles.selected:''}`} onClick={()=>{setSelectedDay(d);setSelectedSlot('')}}><span className={styles.dayLabel}>{d.label}</span><span className={styles.daySub}>{d.sub}</span></button>)}</div>{selectedDay&&<div className={styles.slotsWrap}><div className={styles.slotsTitle}>{availability==='loading'?'Checking availability…':availability==='error'?'Live availability unavailable — choose a time and iHub can confirm it':`${selectedDay.full} · ${pickup?'Pickup windows':'Store appointment slots'}`}</div><div className={styles.slotsGrid}>{TIME_SLOTS.map(slot=>{const blocked=unavailable.includes(slot)||slotPast(selectedDay.value,slot);return <button key={slot} disabled={blocked} className={`${styles.slotBtn} ${selectedSlot===slot?styles.selected:''} ${blocked?styles.taken:''}`} onClick={()=>!blocked&&setSelectedSlot(slot)}><span>{slot}</span>{blocked&&<small>{unavailable.includes(slot)?'Unavailable':'Passed'}</small>}</button>})}</div></div>}</>}
        {step===5&&<><div className={styles.cardHeader}><h2>{pickup?'Pickup & customer details':'Customer details'}</h2><p>We use these details to identify the booking and coordinate the repair.</p></div><div className={styles.formGrid}><Field label="Full Name *" value={form.name} onChange={v=>update('name',v)} placeholder="Your name"/><Field label="Phone / WhatsApp *" value={form.phone} onChange={v=>update('phone',v)} placeholder="+91 9XXXXXXXXX" type="tel"/><Field label="Email (optional)" value={form.email} onChange={v=>update('email',v)} placeholder="you@example.com" type="email"/><Field label="Exact Device Model *" value={form.model} onChange={v=>update('model',v)} placeholder="e.g. iPhone 14 Pro"/>{pickup&&<><Field label="House / Building & Street *" value={form.address} onChange={v=>update('address',v)} placeholder="Pickup address" wide/><Field label="Area *" value={form.area} onChange={v=>update('area',v)} placeholder="Area / locality"/><Field label="Pincode *" value={form.pincode} onChange={v=>update('pincode',v)} placeholder="629..." inputMode="numeric"/><Field label="Landmark" value={form.landmark} onChange={v=>update('landmark',v)} placeholder="Nearby landmark"/><Field label="Google Maps link (optional)" value={form.mapLink} onChange={v=>update('mapLink',v)} placeholder="Paste shared map location link"/></>}<label className={`${styles.field} ${styles.wide}`}><span>Issue / Notes</span><textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Tell us more about the issue, device condition or pickup instructions" rows="4"/></label></div>{form.phone&&!phoneOk&&<p className={styles.validation}>Enter a valid mobile number with 10 to 15 digits.</p>}{pickup&&form.pincode&&!pincodeOk&&<p className={styles.validation}>Enter a valid 5 to 8 digit pincode.</p>}</>}
        {step===6&&<><div className={styles.cardHeader}><h2>Confirm your request</h2><p>Review the details before submitting.</p></div><div className={styles.summary}><Summary label="Method" value={pickup?'Free Pickup & Delivery':'Visit iHub Store'}/><Summary label="Device" value={`${device} · ${form.model}`}/><Summary label="Repair" value={service}/><Summary label={pickup?'Pickup':'Appointment'} value={`${selectedDay?.full} · ${selectedSlot}`}/><Summary label="Customer" value={`${form.name} · ${form.phone}`}/>{pickup&&<Summary label="Address" value={`${form.address}, ${form.area}${form.landmark?`, ${form.landmark}`:''} · ${form.pincode}`}/>}<Summary label="Notes" value={form.notes||'—'}/></div><div className={styles.policyNote}><Icon name="shield" size={18}/><span>By submitting, you are requesting an appointment/pickup. Final repair price, parts option and repair-specific warranty are confirmed after diagnosis. <Link to="/repair-policy">Read repair policy</Link>.</span></div></>}
        {error&&<p className={styles.error}>{error}</p>}
        <div className={styles.navRow}>{step>1&&<button className="btn-secondary" onClick={back}>Back</button>}<div style={{flex:1}}/>{step<6?<button className="btn-primary brand-grad" onClick={next} disabled={!canProceed()}>Continue →</button>:<button className="btn-primary brand-grad" onClick={submit} disabled={submitStatus==='sending'}>{submitStatus==='sending'?'Submitting…':pickup?'Request Free Pickup':'Confirm Booking'}</button>}</div>
      </motion.div></AnimatePresence></div>
    </div></div></section>
  </>;
}

function Field({label,value,onChange,placeholder,type='text',wide=false,inputMode}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span><input type={type} inputMode={inputMode} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Summary({label,value}){return <div className={styles.summaryRow}><span className={styles.summaryLabel}>{label}</span><span className={styles.summaryVal}>{value}</span></div>}
